// Constants for the CustomizeScreen component

export const IMAGE_CONSTRAINTS = {
  MAX_WIDTH: 800,
  MAX_HEIGHT: 600,
  MIN_WIDTH: 300,
  MIN_HEIGHT: 200,
} as const;

export const STICKER_DEFAULTS = {
  SCALE: 0.5,
  ROTATION: 0,
  BASE_Z_INDEX: 100,
  APPROXIMATE_WIDTH: 200,
  APPROXIMATE_HEIGHT: 200,
} as const;

export const RESIZE_CONFIG = {
  MIN_SCALE: 0.1,
  MAX_SCALE: 2,
  SENSITIVITY: 200,
} as const;

export const ROTATION_CONFIG = {
  SPEED: 0.3,
  CLICK_INCREMENT: 45,
  MOMENTUM_THRESHOLD: 0.05,
  MOMENTUM_MULTIPLIER: 100,
} as const;

export const ANIMATION_CONFIG = {
  FAST_ROTATION_DURATION: 0.02,
  SPRING_STIFFNESS: 200,
  SPRING_DAMPING: 25,
  HOVER_DURATION: 0.2,
} as const;

export const UI_SPACING = {
  ROTATION_HANDLE_TOP: -35,
  ROTATION_HANDLE_SIZE: 24,
  DELETE_BUTTON_TOP: -10,
  DELETE_BUTTON_RIGHT: -10,
  DELETE_BUTTON_SIZE: 20,
  RESIZE_HANDLE_SIZE: 12,
  RESIZE_HANDLE_OFFSET: -6,
  TOOLTIP_TOP: -80,
  LINE_HEIGHT: 23,
  LINE_TOP: -12,
} as const;

export const Z_INDICES = {
  LINE: 999,
  HANDLES: 2000,
  TOOLTIP: 3000,
  CONTEXT_MENU: 10000,
  SELECTED_BOOST: 1000,
} as const;